/*
 * Generated by saveVersion.sh
 */
@HiveVersionAnnotation(version="3.1.3000.7.1.1.0-565", shortVersion="3.1.0",
                         revision="5b6f1787eb6263d9fbd5e98b0e81e6fea505d477", branch="(HEAD detached at 5b6f1787eb)",
                         user="jenkins", date="Wed May 20 18:30:18 UTC 2020", url="git://ubuntu18-build-ljhh7/grid/0/jenkins/workspace/workspace/CDH-parallel-ubuntu18/SOURCES/hive",
                         srcChecksum="f231c5ed03bd6beaae972032b1325fb6")
package org.apache.hive.common;
